//! Loading of the training data set from its JSON file.
//!
//! The data set was generated by Gemini : the square meters and the room count of
//! a flat are the inputs, its monthly rental price is the expected output.

use serde::Deserialize;
use std::path::Path;

use crate::without_feature_scaling::N;

/// The default place the training data set is read from, relative to the project root.
pub const DEFAULT_PATH: &str = "data/gemini_created_data_set.json";

/// The JSON file as it is written on the disk : the inputs and the outputs are two
/// separate arrays, and a sample is a row of `inputs` together with the value at the
/// same index of `outputs`.
#[derive(Deserialize)]
struct RawDataSet {
    inputs: Vec<Vec<f64>>,
    outputs: Vec<f64>,
}

/// A training data set whose samples are known to carry exactly [`N`] features.
pub struct DataSet {
    pub inputs: Vec<[f64; N]>,
    pub outputs: Vec<f64>,
}

impl DataSet {
    /// Reads and parses the data set at `path`.
    ///
    /// # Panics
    ///
    /// Panics if the file cannot be read, if it is not valid JSON, or if one of the
    /// samples does not carry exactly [`N`] features.
    pub fn load(path: impl AsRef<Path>) -> Self {
        let path = path.as_ref();

        let json = std::fs::read_to_string(path).unwrap_or_else(|error| {
            panic!(
                "Data set file could not be read : {} ({error})\n\
                 Hint : the path is relative to the project root, run the program with `cargo run`.",
                path.display()
            )
        });

        let raw: RawDataSet = serde_json::from_str(&json)
            .unwrap_or_else(|error| panic!("Data set file is not valid JSON : {error}"));

        let inputs = raw
            .inputs
            .into_iter()
            .enumerate()
            .map(|(i, sample)| {
                let sample_length = sample.len();
                <[f64; N]>::try_from(sample).unwrap_or_else(|_| {
                    panic!(
                        "Sample {i} of the data set has {sample_length} features, \
                         but every sample must have exactly {N} features!!"
                    )
                })
            })
            .collect();

        Self {
            inputs,
            outputs: raw.outputs,
        }
    }
}
